# Generated by Django 3.2.13 on 2022-07-03 21:41

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_first_name', models.CharField(max_length=100)),
                ('member_last_name', models.CharField(max_length=100)),
                ('member_email_address', models.EmailField(max_length=254)),
                ('member_image', models.ImageField(default='', upload_to='photos/%Y/%m/%d/')),
                ('member_bio', tinymce.models.HTMLField(blank=True)),
                ('member_date_joined', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
