# Generated by Django 3.2.13 on 2022-07-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20220704_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='member_is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
